### ISSUE TITLE
Lab issue template

### ISSUE THREAD

**Issue by jsstevenson** [GenomicMedLab/wagner-lab-issues#20]
More or less already written out in the lab notebook, but we could implement it via the github issue template system: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

**Comment by korikuzma** [comment]
I think we should either have the developers meet for this or we make an initial template here or in lab-knowledgebase and make a PR so we can discuss. 

I assume we'd want one for bug + feature request? Do we want other templates?  

Honestly, it might be nice to use this repo or make a separate private repo where other lab members can post questions / issues to developers (in cases where we wouldn't want to make an issue in the project repo). I'm just leaning towards this because I'm not sure if people would follow what's in the templates when slacking

**Comment by korikuzma** [comment]
Moved this issue to the software-templates [here](https://github.com/GenomicMedLab/software-templates/issues/14)
